### DISCUSSION TITLE
Integrating OHIF with Orthanc & MONAI Label (Docker Compose)

### DISCUSSION THREAD

**Discussion by fisherboneee** [Project-MONAI/MONAILabel#1102] [Q&A] [answered]
### CONFIGURATION SETUP

Hi, I wanted to integrate OHIF Viewer with Orthanc & MONAI Label server. Orthanc and OHIF Viewer integrated successfully but I can't get MONAI Label server to connect with OHIF Viewer via Orthanc DICOMWeb.

I use [this code sample](https://bitbucket.org/osimis/orthanc-setup-samples/src/master/docker/ohif/) to integrate Orthanc with OHIF Viewer.

And then in the **compose.yaml**, I modified it to include MONAI Label installation in the Docker Compose.

```
services:
    nginx:
        build: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 81:81
        depends_on:
            - orthanc

    orthanc:
        image: osimis/orthanc:master-unstable
        restart: unless-stopped
        environment:
            ORTHANC__NAME: 'Orthanc for OHIF'

            DICOM_WEB_PLUGIN_ENABLED: 'true'

            ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER: 'true'
            ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_PUBLIC_ROOT: 'http://localhost:81/Viewer/'

            ORTHANC__DICOM_WEB__ENABLE: 'true'

            ORTHANC__REGISTERED_USERS: |
                {"demo": "demo"}

            VERBOSE_STARTUP: 'true'

    monailabel-server: # Project Name
        container_name: monailabel-container # Container Name
        image: projectmonai/monailabel # Image that being pulled from Docker Hub, it will use local image instead if already pulled
        # This is the same as passing `--gpus all` command when running Docker CLI
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        stdin_open: true # docker run -i flag
        tty: true # docker run -t flag
        # Expose port to access from host
        ports:
            - 8000:8000
        # IPC set to host
        ipc: 'host'

        # Attach volume to a path that need to be save
        volumes:
            - orthanc-storage:/var/lib/orthanc/db/
            - monailabel_volume:/opt/monai # Volume name and directory wants to be save, must match the volume name below

volumes:
    orthanc-storage:
    monailabel_volume:

```

After that, I ran `docker compose up -d --build` to start the service.

When the service is up, I type in `docker exec -it monailabel-container /bin/bash` to get inside the container.

From there, I ran `monailabel apps --download --name radiology --output apps` command to download Radiology sample apps.

Lastly, I ran `monailabel start_server --app apps/radiology --studies http://127.0.0.1:80/dicom-web --conf models deepedit`

### THE PROBLEM

I am able to upload data in Orthanc through this URL: http://localhost/ui/app/
and access it with the OHIF Viewer by navigating through http://localhost:81 or clicking _"View in OHIF"_ button in Orthanc

**HOWEVER**
I am not able to access http://localhost:8000/ohif and it says 

> {"detail":"Resource NOT Found"}

But I am able to access http://localhost:8000 and it will give me the list of MONAI Label API.

Can someone help me?
