### DISCUSSION TITLE
Problem with using Docker for setting-up MONAI Label with OHIF

### DISCUSSION THREAD

**Discussion by philosGit** [Project-MONAI/MONAILabel#1423] [Q&A] [answered]
Hi,

This is the first time for me writing to the community so please inform me, if I can improve in some way.
I am currently trying to use MONAI Label with Docker. Therefore, I followed the steps in the MONAI Label Github repository and the quickstart guide. I tried all upcoming steps on my Windows 10 laptop (docker version 23.0.5) and in a VirtualBox with Ubuntu 18.04.3 (docker version 20.10.21), just to make sure, that the problem is not Windows specific. I also tried it for the latest commit of MONAI Label [https://github.com/Project-MONAI/MONAILabel/commit/737a581fade1d473fa6892703a605544ec48a367] and the tag 0.5.2, since this should work with Docker according to the video here [https://github.com/Project-MONAI/MONAILabel/issues/594]. My steps are as following:
- Install Orthanc server as described in the quickstart guide for the used OS. Check it by accessing http://127.0.0.1:8042/ and upload an example DICOM image.
- Open a terminal to start the docker container using: `sudo docker run --rm -ti --ipc=host --net=host projectmonai/monailabel:latest bash`
- Within the container download the app and start the server. Please, see the output section below.

Output:
`root@abc-VirtualBox:/opt/monai# monailabel start_server --app apps/radiology --studies http://127.0.0.1:8042/dicom-web --conf models deepedit
Using PYTHONPATH=/opt:

2023-05-08 09:58:45,427 - USING:: version = False
2023-05-08 09:58:45,430 - USING:: app = /opt/monai/apps/radiology
2023-05-08 09:58:45,431 - USING:: studies = http://127.0.0.1:8042/dicom-web
2023-05-08 09:58:45,431 - USING:: verbose = INFO
2023-05-08 09:58:45,431 - USING:: conf = [['models', 'deepedit']]
2023-05-08 09:58:45,432 - USING:: host = 0.0.0.0
2023-05-08 09:58:45,432 - USING:: port = 8000
2023-05-08 09:58:45,432 - USING:: uvicorn_app = monailabel.app:app
2023-05-08 09:58:45,433 - USING:: ssl_keyfile = None
2023-05-08 09:58:45,433 - USING:: ssl_certfile = None
2023-05-08 09:58:45,433 - USING:: ssl_keyfile_password = None
2023-05-08 09:58:45,433 - USING:: ssl_ca_certs = None
2023-05-08 09:58:45,433 - USING:: workers = None
2023-05-08 09:58:45,434 - USING:: limit_concurrency = None
2023-05-08 09:58:45,434 - USING:: access_log = False
2023-05-08 09:58:45,434 - USING:: log_config = None
2023-05-08 09:58:45,434 - USING:: dryrun = False
2023-05-08 09:58:45,434 - USING:: action = start_server
2023-05-08 09:58:45,435 - ENV SETTINGS:: MONAI_LABEL_API_STR = 
2023-05-08 09:58:45,435 - ENV SETTINGS:: MONAI_LABEL_PROJECT_NAME = MONAILabel
2023-05-08 09:58:45,435 - ENV SETTINGS:: MONAI_LABEL_APP_DIR = 
2023-05-08 09:58:45,435 - ENV SETTINGS:: MONAI_LABEL_STUDIES = 
2023-05-08 09:58:45,436 - ENV SETTINGS:: MONAI_LABEL_AUTH_ENABLE = False
2023-05-08 09:58:45,436 - ENV SETTINGS:: MONAI_LABEL_AUTH_DB = 
2023-05-08 09:58:45,436 - ENV SETTINGS:: MONAI_LABEL_APP_CONF = '{}'
2023-05-08 09:58:45,436 - ENV SETTINGS:: MONAI_LABEL_TASKS_TRAIN = True
2023-05-08 09:58:45,436 - ENV SETTINGS:: MONAI_LABEL_TASKS_STRATEGY = True
2023-05-08 09:58:45,437 - ENV SETTINGS:: MONAI_LABEL_TASKS_SCORING = True
2023-05-08 09:58:45,437 - ENV SETTINGS:: MONAI_LABEL_TASKS_BATCH_INFER = True
2023-05-08 09:58:45,437 - ENV SETTINGS:: MONAI_LABEL_DATASTORE = 
2023-05-08 09:58:45,437 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_URL = 
2023-05-08 09:58:45,437 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_USERNAME = 
2023-05-08 09:58:45,437 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PASSWORD = 
2023-05-08 09:58:45,438 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_API_KEY = 
2023-05-08 09:58:45,438 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_CACHE_PATH = 
2023-05-08 09:58:45,438 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PROJECT = 
2023-05-08 09:58:45,438 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_ASSET_PATH = 
2023-05-08 09:58:45,438 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_DSA_ANNOTATION_GROUPS = 
2023-05-08 09:58:45,438 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_USERNAME = 
2023-05-08 09:58:45,439 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PASSWORD = 
2023-05-08 09:58:45,439 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_PATH = 
2023-05-08 09:58:45,439 - ENV SETTINGS:: MONAI_LABEL_QIDO_PREFIX = None
2023-05-08 09:58:45,439 - ENV SETTINGS:: MONAI_LABEL_WADO_PREFIX = None
2023-05-08 09:58:45,439 - ENV SETTINGS:: MONAI_LABEL_STOW_PREFIX = None
2023-05-08 09:58:45,439 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_FETCH_BY_FRAME = False
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CONVERT_TO_NIFTI = True
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_SEARCH_FILTER = '{"Modality": "CT"}'
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_EXPIRY = 180
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PROXY_TIMEOUT = 30.0
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_READ_TIMEOUT = 5.0
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_AUTO_RELOAD = True
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd", "*.jpg", "*.png", "*.tif", "*.svs", "*.xml"]'
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_SERVER_PORT = 8000
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_CORS_ORIGINS = '[]'
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_SESSIONS = True
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_SESSION_PATH = 
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_SESSION_EXPIRY = 3600
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_INFER_CONCURRENCY = -1
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_INFER_TIMEOUT = 600
2023-05-08 09:58:45,440 - ENV SETTINGS:: MONAI_LABEL_AUTO_UPDATE_SCORING = True
2023-05-08 09:58:45,440 - 
Allow Origins: ['*']
[2023-05-08 09:58:46,302] [395] [MainThread] [INFO] (uvicorn.error:75) - Started server process [395]
[2023-05-08 09:58:46,306] [395] [MainThread] [INFO] (uvicorn.error:45) - Waiting for application startup.
[2023-05-08 09:58:46,307] [395] [MainThread] [INFO] (monailabel.interfaces.utils.app:38) - Initializing App from: /opt/monai/apps/radiology; studies: http://127.0.0.1:8042/dicom-web; conf: {'models': 'deepedit'}
[2023-05-08 09:58:46,412] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2023-05-08 09:58:46,435] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.localization_vertebra.LocalizationVertebra'>
[2023-05-08 09:58:46,439] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.localization_spine.LocalizationSpine'>
[2023-05-08 09:58:46,440] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_3d.Deepgrow3D'>
[2023-05-08 09:58:46,445] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepedit.DeepEdit'>
[2023-05-08 09:58:46,451] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_spleen.SegmentationSpleen'>
[2023-05-08 09:58:46,459] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation.Segmentation'>
[2023-05-08 09:58:46,461] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_2d.Deepgrow2D'>
[2023-05-08 09:58:46,462] [395] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_vertebra.SegmentationVertebra'>
[2023-05-08 09:58:46,463] [395] [MainThread] [INFO] (main:87) - +++ Adding Model: deepedit => lib.configs.deepedit.DeepEdit
[2023-05-08 09:58:46,463] [395] [MainThread] [INFO] (monailabel.utils.others.generic:182) - Downloading resource: /opt/monai/apps/radiology/model/pretrained_deepedit_dynunet.pt from https://github.com/Project-MONAI/MONAILabel/releases/download/data/deepedit_dynunet_multilabel.pt
pretrained_deepedit_dynunet.pt: 118MB [00:05, 21.2MB/s]                         
2023-05-08 09:58:52,320 - INFO - Downloaded: /opt/monai/apps/radiology/model/pretrained_deepedit_dynunet.pt
2023-05-08 09:58:52,320 - INFO - Expected md5 is None, skip md5 check for file /opt/monai/apps/radiology/model/pretrained_deepedit_dynunet.pt.
[2023-05-08 09:58:55,274] [395] [MainThread] [INFO] (lib.configs.deepedit:144) - EPISTEMIC Enabled: False; Samples: 5
[2023-05-08 09:58:55,274] [395] [MainThread] [INFO] (lib.configs.deepedit:148) - TTA Enabled: False; Samples: 5
[2023-05-08 09:58:55,275] [395] [MainThread] [INFO] (main:91) - +++ Using Models: ['deepedit']
[2023-05-08 09:58:55,275] [395] [MainThread] [INFO] (monailabel.interfaces.app:129) - Init Datastore for: http://127.0.0.1:8042/dicom-web
[2023-05-08 09:58:55,275] [395] [MainThread] [INFO] (monailabel.interfaces.app:149) - Using DICOM WEB: http://127.0.0.1:8042/dicom-web
dcmqi-1.2.4-linux.tar.gz: 20.6MB [00:01, 11.1MB/s]                              
2023-05-08 09:58:57,229 - INFO - Downloaded: /tmp/tmp53dli1rs/dcmqi-1.2.4-linux.tar.gz
2023-05-08 09:58:57,230 - INFO - Expected md5 is None, skip md5 check for file /tmp/tmp53dli1rs/dcmqi-1.2.4-linux.tar.gz.
2023-05-08 09:58:57,230 - INFO - Writing into directory: /tmp/tmp5gz9xxoz.
[2023-05-08 09:58:57,830] [395] [MainThread] [INFO] (monailabel.datastore.dicom:62) - DICOMWeb Datastore (cache) Path: /root/.cache/monailabel/dicom/488fca1f7f3f98331f6f7756beca0d35; FetchByFrame: False
[2023-05-08 09:58:57,831] [395] [MainThread] [INFO] (monailabel.datastore.dicom:63) - DICOMWeb Convert To Nifti: True
[2023-05-08 09:58:57,832] [395] [MainThread] [INFO] (monailabel.datastore.local:128) - Auto Reload: True; Extensions: ('*.nii.gz', '*.nii')
[2023-05-08 09:58:57,833] [395] [MainThread] [INFO] (monailabel.datastore.local:574) - Invalidate count: 0
[2023-05-08 09:58:57,833] [395] [MainThread] [INFO] (monailabel.datastore.local:148) - Start observing external modifications on datastore (AUTO RELOAD)
[2023-05-08 09:58:57,835] [395] [MainThread] [INFO] (main:117) - +++ Adding Inferer:: deepedit => <lib.infers.deepedit.DeepEdit object at 0x7fd0f000c820>
[2023-05-08 09:58:57,838] [395] [MainThread] [INFO] (main:117) - +++ Adding Inferer:: deepedit_seg => <lib.infers.deepedit.DeepEdit object at 0x7fd0f000ceb0>
[2023-05-08 09:58:57,838] [395] [MainThread] [INFO] (main:173) - {'deepedit': <lib.infers.deepedit.DeepEdit object at 0x7fd0f000c820>, 'deepedit_seg': <lib.infers.deepedit.DeepEdit object at 0x7fd0f000ceb0>, 'Histogram+GraphCut': <monailabel.scribbles.infer.HistogramBasedGraphCut object at 0x7fd0f000cd60>, 'GMM+GraphCut': <monailabel.scribbles.infer.GMMBasedGraphCut object at 0x7fd0f0032c40>}
[2023-05-08 09:58:57,838] [395] [MainThread] [INFO] (main:186) - +++ Adding Trainer:: deepedit => <lib.trainers.deepedit.DeepEdit object at 0x7fd0f0032d60>
[2023-05-08 09:58:57,839] [395] [MainThread] [INFO] (monailabel.utils.sessions:51) - Session Path: /root/.cache/monailabel/sessions
[2023-05-08 09:58:57,839] [395] [MainThread] [INFO] (monailabel.utils.sessions:52) - Session Expiry (max): 3600
[2023-05-08 09:58:57,839] [395] [MainThread] [INFO] (monailabel.interfaces.app:467) - App Init - completed
[2023-05-08 09:58:57,840] [timeloop] [INFO] Starting Timeloop..
[2023-05-08 09:58:57,840] [395] [MainThread] [INFO] (timeloop:60) - Starting Timeloop..
[2023-05-08 09:58:57,840] [timeloop] [INFO] Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x7fd0f0033310>
[2023-05-08 09:58:57,840] [395] [MainThread] [INFO] (timeloop:42) - Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x7fd0f0033310>
[2023-05-08 09:58:57,847] [timeloop] [INFO] Timeloop now started. Jobs will run based on the interval set
[2023-05-08 09:58:57,847] [395] [MainThread] [INFO] (timeloop:63) - Timeloop now started. Jobs will run based on the interval set
[2023-05-08 09:58:57,847] [395] [MainThread] [INFO] (uvicorn.error:59) - Application startup complete.
[2023-05-08 09:58:57,847] [395] [MainThread] [INFO] (uvicorn.error:206) - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
`

I can access Orthanc (http://127.0.0.1:8042/) and the MONAI Label server (http://127.0.0.1:8000/), but when I try to open the OHIF viewer (http://127.0.0.1:8000/ohif/) it says, that {"detail":"Resource NOT Found"} and in the terminal where I executed the start server command the following shows up: 
`[2023-05-08 09:59:17,585] [395] [MainThread] [INFO] (monailabel.endpoints.ohif:38) - /opt/conda/lib/python3.8/site-packages/monailabel/endpoints/static/ohif/index.html`
I investigate by checking the path mentioned and there is no index.html file there (not even a ohif directory in the static folder can be found). Therefore, I also tried building the ohif viewer plugin again in the container, just to make sure that it is there and still nothing is there. I also checked the folder in the path "/opt/conda/monailabel" for its content and could not find a index.html.

Additionally, I tried using MONAI Label with Anaconda and installing it with pip. This works out well and everything is working (also OHIF is reachable). So I guess the problem has to do with the Docker setup?

After figuring out the basics my aim is to run the MONAI Label server in a virtual machine on the Google Cloud Platform (GCP), since I lack the processing power (no GPU). So I also checked [https://github.com/Project-MONAI/MONAILabel/discussions/1102] to set up a docker compose file, but since I am rather new to Docker and don't have much experience in setting-up webservices, I am not quite sure on how to configure Nginx to redirect and show me the OHIF viewer. So also this option is at the moment not working for me.

My question now is, if somebody knows what I am doing wrong here and would be so kind to help me out. Every hint is appreciated. Thank you very much in advance.

**Comment by tangy5** [comment]
HI @philosGit ， thanks for posting. I guess since you are running docker to use MONAI Label, the http:/0.0.0.0/#### or 127.0.0.1/#### is not the real host IP. If you can confirm you can open the APIs via the host address. You can check whether the file /opt/conda/lib/python3.8/site-packages/monailabel/endpoints/static/ohif/index.html exists. If no, I think the OHIF is not pre-build. You can build the OHIF you own following this papge, cd to the OHIF plugin folder and `sh build.sh`.   https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif#development-setup

Can you double confirm, if the latest Docker doesn't pre-build the OHIF, we will investigate. Thanks.

**Reply by SachidanandAlle** [reply]
Looks like OHIF is not pre built in the docker image.. can you share when you pulled that image?

**Reply by philosGit** [reply]
Hi @tangy5,
Thank you very much for your fast reply and your efford. I have checked the availability of the 'index.html' and I can't find it.
The only file, which is located in the directory '/usr/local/lib/python3.8/dist-packages/monailabel/endpoints/static' after starting the docker container is 'favicon.ico'.
As you suggested I also build the the ohif viewer within the container using `sh build.sh` and this is the output:
`lerna success run Ran npm script 'build:viewer' in 1 package in 157.1s:
lerna success - @ohif/viewer
Done in 158.74s.
mv: cannot move './Viewers/platform/viewer/dist' to '/usr/local/monailabel/plugins/ohif/../../monailabel/endpoints/static/ohif': No such file or directory
Copied OHIF to /usr/local/monailabel/plugins/ohif/../../monailabel/endpoints/static/ohif` 
Still if I search for folders with the name ohif using the find command the only path I get is 
'/usr/local/monailabel/plugins/ohif' and still no files were added to the static endpoints directory.
Also, in the '/usr/local/lib/python3.8/dist-packages/monailabel/endpoints/static' directory only the 'favicon.ico' file can be found.
So I am not really sure where the ohif viewer is saved afterwards, since it still can't be opened at http://127.0.0.1:8000/ohif/. 
The page still states: '{"detail":"Resource NOT Found"}'. Maybe this is also related to what @SachidanandAlle wrote about node?

Hi @SachidanandAlle,
Thank you as well for your fast reply and your efford.
Should I still share the image with you, since you already added a new post pointing out the missing pre-build of docker?
I also checked again in the container using `monailabel --version` and the output is 'MONAILabel rev id: 737a581fade1d473fa6892703a605544ec48a367'.
It's great to hear, that you can possibly fix it soon. I am really looking forward to use MONAI Label. If I can help, please let me know. Thank you very much in advance.

**Comment by SachidanandAlle** [comment]
I  can confirm some recent node (version) deprecation on the docker build causing the issue.. it shall be fixed soon..

**Comment by sscotti** [comment]
I am having a similar issue.  I'd actually like to build either all of MONAI or just MONAI label with the OHIF integration in Docker using docker-compose.yml integrated with an Orthanc instance.  What I currently have in docker-compose.yml for the MONAI label part is below.  That seems to at least build and mostly work, except the ohif route gives a 404 error.  It might be nice to include a Dockerfile so I could customize it a little and I would prefer to just install all of MONAI with Docker and then also setup MONAI Label within that, if that is possible.  I know how to add an Orthanc Instance already.  I am using host port 8001 because it is taken by another service.

```
  monailabel-server:

    # build: monailabel-server
    image: projectmonai/monailabel
    stdin_open: true # docker run -i flag
    tty: true # docker run -t flag
    # Expose port to access from host
    ports:
        - 8001:8000
    # IPC set to host
    ipc: 'host'
    environment:
      BUILD_OHIF: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # Attach volume to a path that need to be save
    volumes:
        - orthanc-storage:/var/lib/orthanc/db/
        - monailabel_volume:/opt/monai # Volume name and directory wants to be save, must match the volume name below
```

**Reply by SachidanandAlle** [reply]
Working on the fix.. some node dependency has been broken on the OHIF side..

**Reply by SachidanandAlle** [reply]
Yes.. you can simply include monai docker and do pip install monailabel (latest RC version) as well.. instead of using monailabel docker..

Please refer dockerfile of Monailabel.. we do exactly the same.. instead of building pip package for monailabel.. you can pull latest version of Monailabel

**Reply by sscotti** [reply]
Like this ?  I think I tried that a couple of times already and uncommented the '# build: monailabel-server' in my compose, but I think I ran into an error at the very end regarding setup.py.  I can try again.  I am just getting started using MONAI, but if it is possible to build a conatiner that has all of MONAI in it, and then setup MONAI label with that, that would be better because I suspect I'll want to use many of the other packages later.  Thanks.
```
# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To build with a different base image
# please run `./runtests.sh --clean && DOCKER_BUILDKIT=1 docker build -t projectmonai/monailabel:latest .`
# to use different version of MONAI pass `--build-arg MONAI_IMAGE=...`

ARG MONAI_IMAGE=projectmonai/monai:1.2.0rc5

FROM ${MONAI_IMAGE} as build
LABEL maintainer="monai.contact@gmail.com"
ARG BUILD_OHIF=true

ADD . /opt/monailabel/
RUN apt update -y && apt install openslide-tools npm -y && npm install --global yarn
RUN python -m pip install --upgrade --no-cache-dir pip setuptools wheel twine \
    && cd /opt/monailabel \
    && BUILD_OHIF=${BUILD_OHIF} python setup.py sdist bdist_wheel --build-number $(date +'%Y%m%d%H%M')

FROM ${MONAI_IMAGE}
LABEL maintainer="monai.contact@gmail.com"

COPY --from=build /opt/monailabel/dist/monailabel* /opt/monailabel/dist/
RUN python -m pip install --upgrade --no-cache-dir pip \
    && python -m pip install /opt/monailabel/dist/monailabel*.whl
```

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/pull/1424 this will help to solve the problem.
Once it's merged, you can refer https://github.com/Project-MONAI/MONAILabel/blob/main/Dockerfile to include in your own builds

if you have monai docker and you are not looking build monaibel from source then `pip install monailabel>=0.7.0rc6 -U` should be enough to add.  PIP version of the packages has OHIF pre-built.. so just installing via pip is good enough (u don't have to build OHIF explicitly)

```
ARG MONAI_IMAGE=projectmonai/monai:1.2.0rc6

FROM ${MONAI_IMAGE}
LABEL maintainer="monai.contact@gmail.com"

RUN python -m pip install --upgrade --no-cache-dir pip && python -m monailabel>=0.7.0rc6
```

**Reply by sscotti** [reply]
Thank you very much.  That should help.  I was hoping to get the OHIF viewer to work.

**Reply by sscotti** [reply]
I had a little bit of an issue with that, maybe a cache issue actually, so I just cloned the GitHub repo and built an image using the docker file from there on my host, and tagged it so I have a good local image to work with.  I then use that in my docker-compose.yml to bring up a someone integrated package having an orthanc instance and some databases also.  I haven't quite figured out how to start up the label server without it shutting down automatically, except using docker exec after the container starts.  At least something to work with now.

BTW, I think you have some typos on this page also:  [QuickStart](https://docs.monai.io/projects/label/en/latest/quickstart.html)

localhost, not locahost.

`monailabel start_server --app radiology --studies http://locahost:8042/dicom-web --conf models deepedit`

![image](https://github.com/Project-MONAI/MONAILabel/assets/236933/2595b6b7-8c71-452a-b346-ea15340e0357)

```

version: "3.8"

services:

  pacs:
  
    build: pacs
    image: sdscotti/monai-pacs
    depends_on:
      - postgres_index-db
      - mysql_db
    restart: unless-stopped
    ports:
      - "4242:4242"
      - "8042:8042"     
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./orthanc_python:/python
      - ./orthanc_lua:/lua-scripts
      - ./pacs:/etc/orthanc
      - ./tls_dicom:/etc/orthanc/tls_dicom
      - ./ServeFolders:/development
    environment:
      ORTHANC__NAME: "MONAI"
      ORTHANC__DICOM_AET: "MONAI"
      # POSTGRES & MYSQL
      ORTHANC__POSTGRESQL__HOST: "postgres_index-db"
      
    env_file:
    - ./config/.env
    - ./config/.env_pacs

  monailabel-server:

    image: sdscotti/monailabel
    stdin_open: true # docker run -i flag
    tty: true # docker run -t flag
    # Expose port to access from host
    ports:
        - 8001:8000
    # IPC set to host
    ipc: 'host'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # Attach volume to a path that need to be save
    volumes:
        - orthanc-storage:/var/lib/orthanc/db/
        # - monailabel_volume:/opt/monai # Volume name and directory wants to be save, must match the volume name below

  postgres_index-db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - orthanc_db:/var/lib/postgresql/data
      - type: tmpfs
        target: /pg_stat_tmp
        tmpfs:
          # 256 Mb - beware the default, it's infinity(!)
          size: 268435456
    # fixes this WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted 
    # command:  postgres -c stats_temp_directory=/tmp
    # this turns on logging for postgres, with the log file located on the host in the log folder, not really needed except for debugging
    # command: ["postgres", "-c", "logging_collector=on", "-c", "log_statement=all"]
    
    env_file:
    - ./config/.env


  mysql_db:
  
    image: mysql:8.0.29
    # image: mysql/mysql-server:8.0.29-1.2.8-server-amd64
    # use the image below for M1 Mac
    # image: mysql/mysql-server:8.0.29-1.2.8-server-aarch64
    container_name: mysql_db
    #--general-log-file=/var/lib/mysql/mysql-log.log
    command: >
      mysqld 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --max-allowed-packet=67108864
      --disable-log-bin
      --general-log=OFF
      --binlog_expire_logs_seconds=259200
  
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    security_opt:
      - seccomp:unconfined
    tty: true
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      
    env_file:
    - ./config/.env

    volumes:
      - mysql:/var/lib/mysql/
      - ./mysql_init:/docker-entrypoint-initdb.d
      - ./db_backups:/db_backups


volumes:
    orthanc_db:
    orthanc-storage:
    mysql:
    # monailabel_volume:
```
